### PR TITLE
Removing animation and running end scene with coroutine

### LINKED ISSUE #2: Can't disable white laser on intro-scene
White laser can't be disabled via script or via editor, strange.

### PR DESCRIPTION
**Pull request by vitallan**
Fix #2 

White laser was used in the "Puzzle" animation, therefore the engine tried to keep it active at all times. Confirmed through removing the animation from scene.

Solved by making the final transition with a coroutine in LaserController.

It's worth checking if the final solution looks better than using the animation.

### CODE REVIEW

**Comment by vitallan** [comment]
Still WIP
Some work still needed to make the final text fade out

**Comment by vitallan** [comment]
all set

**Comment by leonardoobaptistaa** [comment]
it was missing the last two text animations, I added it on the last commit

**Comment by leonardoobaptistaa** [comment]
also, I liked the removal of Animator.
the interface is buggy, doing it by code seems better.

**Pull request merged**
